sudo: required
services:
    - docker
before_install:
    - docker build -t santhoshasokan/react-test -f ./client/Dockerfile.dev ./client
 
script:
    - docker run -e CI=true santhoshasokan/react-test npm test -- --coverage    

after_success:
    - docker build -t santhoshasokan/multi-client ./client 
    - docker build -t santhoshasokan/multi-nginx ./nginx
    - docker build -t santhoshasokan/multi-server ./server
    - docker build -t santhoshasokan/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin
    - docker push santhoshasokan/multi-client
    - docker push santhoshasokan/multi-nginx
    - docker push santhoshasokan/multi-server
    - docker push santhoshasokan/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-833385162024
    bucket_path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
