version: '3'
services: 
    postgres:
        image: postgres:10.10
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST_AUTH_METHOD=trust
    redis:
        image: redis
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'    
    api:
        depends_on:
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - C:/Users/aravindh/dockerChallenges/complex/server:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - C:/Users/aravindh/dockerChallenges/complex/worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379    
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - C:/Users/aravindh/dockerChallenges/complex/client:/app